version: '3'

services:
    init:
        build: .
        image: andbox 
    web:
        image: andbox 
        ports:
        - "5000:80"
        volumes:
        - ./server:/opt/sim/server:ro
        - ./challenges:/opt/sim/challenges:ro
        - ./Player:/home/simulator/player
        - ./Bot:/home/simulator/bot
        command: "/opt/sim/setup/web.sh"
    player:
        image: andbox 
        ports:
        - "5001:5000"
        volumes:
        - ./challenges:/opt/sim/challenges:ro
        - ./Player:/home/simulator:ro
        command: "/opt/sim/setup/player.sh"
    bot:
        image: andbox 
        ports:
        - "5002:5000"
        volumes:
        - ./challenges:/opt/sim/challenges:ro
        - ./Bot:/home/simulator:ro
        command: "/opt/sim/setup/web.sh"
        command: "/opt/sim/setup/bot.sh"
